<?php
return [
'events_title'=>'Tourism events','events_intro'=>'Activities and important dates for visitors and communities.','filter_municipality'=>'Filter by municipality','clear'=>'Clear','view_event'=>'View event','no_events'=>'There are no published events yet.','event_data'=>'Event details','place_pending'=>'Location to be confirmed','ends'=>'Ends',
'news_eyebrow'=>'Latest updates','news_title'=>'Tourism news','news_intro'=>'News, announcements and editorial content from the portal.','read_news'=>'Read article','no_news'=>'There is no published news yet.','related'=>'Related',
'weekly_publications'=>'Publications of the week','week_range'=>'From :from to :to','previous_week'=>'Previous week','next_week'=>'Next week','current_week'=>'Current week','no_news_week'=>'There are no publications registered for this week.',
'search_eyebrow'=>'Search','search_title'=>'Search the portal','search_placeholder'=>'Search destinations, events or news','search'=>'Search','no_destination_results'=>'No destinations were found.','no_event_results'=>'No events were found.','no_news_results'=>'No news was found.',
'contact_eyebrow'=>'Let’s talk','contact_intro'=>'Share your questions, experiences, suggestions or complaints. Your opinion helps us improve tourism.','information'=>'Information','information_help'=>'Find the portal’s institutional and business contact information here.','tell_us'=>'Tell us','name'=>'Name','email'=>'Email address','phone'=>'Phone','message_placeholder'=>'Write your message here...','form_error'=>'Review the marked fields and try again.','send'=>'Send message',
'official_directory'=>'Official directory','services_title'=>'Approved tourism services','services_intro'=>'View providers registered through the form and approved by the administration team.','view_category'=>'View category','no_providers'=>'There are currently no approved providers.','all_services'=>'All services','approved_count'=>':count approved provider(s)','no_approved'=>'There are no approved providers yet','register_service'=>'Register a service',
];
