<?php
return [
'events_title'=>'Eventos turísticos','events_intro'=>'Actividades y fechas importantes para visitantes y comunidades.','filter_municipality'=>'Filtrar por municipio','clear'=>'Limpiar','view_event'=>'Ver evento','no_events'=>'No hay eventos publicados todavía.','event_data'=>'Datos del evento','place_pending'=>'Lugar por definir','ends'=>'Finaliza',
'news_eyebrow'=>'Actualidad','news_title'=>'Noticias turísticas','news_intro'=>'Novedades, anuncios y contenido editorial del portal.','read_news'=>'Leer noticia','no_news'=>'No hay noticias publicadas todavía.','related'=>'Relacionado',
'weekly_publications'=>'Publicaciones de la semana','week_range'=>'Del :from al :to','previous_week'=>'Semana anterior','next_week'=>'Semana siguiente','current_week'=>'Semana actual','no_news_week'=>'No hay publicaciones registradas para esta semana.',
'search_eyebrow'=>'Búsqueda','search_title'=>'Buscar en el portal','search_placeholder'=>'Buscar destinos, eventos o noticias','search'=>'Buscar','no_destination_results'=>'No se encontraron destinos.','no_event_results'=>'No se encontraron eventos.','no_news_results'=>'No se encontraron noticias.',
'contact_eyebrow'=>'Conversemos','contact_intro'=>'Comparte tus consultas, experiencias, sugerencias o quejas. Tu opinión nos ayuda a mejorar el turismo.','information'=>'Información','information_help'=>'Completa aquí los datos institucionales o comerciales del portal.','tell_us'=>'Cuéntanos','name'=>'Nombre','email'=>'Correo electrónico','phone'=>'Teléfono','message_placeholder'=>'Escribe aquí tu mensaje...','form_error'=>'Revisa los campos marcados e intenta de nuevo.','send'=>'Enviar mensaje',
'official_directory'=>'Directorio oficial','services_title'=>'Servicios turísticos aprobados','services_intro'=>'Consulta prestadores inscritos mediante el formulario y aprobados por el equipo administrador.','view_category'=>'Ver categoría','no_providers'=>'Sin prestadores aprobados por el momento.','all_services'=>'Todos los servicios','approved_count'=>':count prestador(es) aprobado(s)','no_approved'=>'Todavía no hay prestadores aprobados','register_service'=>'Registrar un servicio',
];
